use sampled;
CREATE TABLE  `E_BOOK` 
   (	`CALLNO` VARCHAR(400) NOT NULL, 
	`NAME` VARCHAR(400), 
	`AUTHOR` VARCHAR(400), 
	`PUBLISHER` VARCHAR(400), 
	`QUANTITY` DOUBLE, 
	`ISSUED` DOUBLE, 
	 CONSTRAINT `E_BOOK_PK` PRIMARY KEY (`CALLNO`) 
   );
   
   CREATE TABLE  `E_LIBRARIAN` 
   (	`ID` DOUBLE NOT NULL, 
	`NAME` VARCHAR(400), 
	`PASSWORD` VARCHAR(400), 
	`EMAIL` VARCHAR(400), 
	`MOBILE` DOUBLE, 
	 CONSTRAINT `E_LIBRARIAN_PK` PRIMARY KEY (`ID`) 
   );
   
   CREATE TABLE  `E_ISSUEBOOK` 
   (	`CALLNO` VARCHAR(400) NOT NULL, 
	`STUDENTID` VARCHAR(400) NOT NULL, 
	`STUDENTNAME` VARCHAR(400), 
	`STUDENTMOBILE` DOUBLE, 
	`ISSUEDDATE` DATETIME, 
	`RETURNSTATUS` VARCHAR(400)
   );